import type { Abi } from "viem";

// Import raw JSON ABIs generated by hardhat-abi-exporter
import OracleRedStoneAdaptorJson from "../abi/OracleRedStoneAdaptor.json";
import OracleAlgebraAdaptorJson from "../abi/OracleAlgebraAdaptor.json";
import OracleChainlinkPushAdaptorJson from "../abi/OracleChainlinkPushAdaptor.json";
import ProTokenJson from "../abi/ProToken.json";
import ProTokenOperationsJson from "../abi/ProTokenOperations.json";
import ProTokenSettingsJson from "../abi/ProTokenSettings.json";
import ProTokenUnmintHandlerJson from "../abi/ProTokenUnmintHandler.json";
import ERC20Json from "../abi/ERC20.json";
import YAssetOperationsHandlerJson from "../abi/YAssetOperationsHandler.json";
import AaveV3YieldHandlerJson from "../abi/AaveV3YieldHandler.json";
import ProTokenPlusJson from "../abi/ProTokenPlus.json";
import ProTokenPlusRewardDistributorJson from "../abi/ProTokenPlusRewardDistributor.json";

// --- ABIs ---
// Export ABIs with proper typing for viem/wagmi

export const oracleRedStoneAdaptorAbi = OracleRedStoneAdaptorJson as Abi;
export const oracleAlgebraAdaptorAbi = OracleAlgebraAdaptorJson as Abi;
export const oracleChainlinkPushAdaptorAbi = OracleChainlinkPushAdaptorJson as Abi;
export const proTokenAbi = ProTokenJson as Abi;
export const proTokenOperationsAbi = ProTokenOperationsJson as Abi;
export const proTokenUnmintHandlerAbi = ProTokenUnmintHandlerJson as Abi;
export const proTokenSettingsAbi = ProTokenSettingsJson as Abi;
export const erc20Abi = ERC20Json as Abi;
export const yAssetOperationsHandlerAbi = YAssetOperationsHandlerJson as Abi;
export const aaveV3YieldHandlerAbi = AaveV3YieldHandlerJson as Abi;
export const proTokenPlusAbi = ProTokenPlusJson as Abi;
export const proTokenPlusRewardDistributorAbi = ProTokenPlusRewardDistributorJson as Abi;
